apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env-project001
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/pattern3/dev-env/namespaces/project001
    repoURL: 'https://github.com/saurav116/GitOps-Patterns.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
