apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env-project003
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: dev-env-project
  source:
    path: apps/pattern3/dev-env/namespaces/project003
    repoURL: https://github.com/saurav116/GitOps-Patterns
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
