apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env-httpbin-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/pattern3/dev-env/apps/httpbin-app
    repoURL: https://github.com/saurav116/GitOps-Patterns
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
