apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: bgdk
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/pattern1/bgd/overlays/bgdk
    repoURL: 'https://github.com/saurav116/GitOps-Patterns.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
source:
  repoURL: 'https://github.com/saurav116/GitOps-Patterns.git'
  path: apps/pattern1/bgd/overlays/bgdk
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: bgdk
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
