apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-env-appset
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/saurav116/GitOps-Patterns
        revision: main
        directories:
          - path: apps/pattern4/prod-env/apps/*
          - path: apps/pattern4/prod-env/namespaces/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/saurav116/GitOps-Patterns
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
