apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demos/pattern3/components/
    repoURL: https://github.com/saurav116/GitOps-Patterns
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
